import {
  DownloadAllSheetsButton,
  DownloadBasicSheetButton,
  DownloadDetailedSheetButton,
  DownloadSheetsHeaderButtons,
} from "@/components/DownloadSheetsButtons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ArrowLeft,
  BarChart3,
  Calculator,
  CheckSquare,
  Clock,
  Printer,
} from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Printable Contraction Tracking Sheets",
  description:
    "Physical backup sheets for tracking contractions when digital tools aren't available. Free downloadable PDF sheets with timing guides and the 5-1-1 rule reference.",
  keywords: [
    "printable contraction tracker",
    "contraction tracking sheet",
    "labor timing sheet",
    "contraction log",
    "paper contraction timer",
    "backup contraction tracker",
    "printable labor tracker",
    "contraction timing chart",
  ],
  alternates: {
    canonical: "/resources/printable-contraction-sheets",
  },
  openGraph: {
    title: "Printable Contraction Tracking Sheets | Contracking",
    description:
      "Physical backup sheets for tracking contractions when digital tools aren't available.",
    url: "https://contracking.me/resources/printable-contraction-sheets",
    images: ["/og-image.jpg"],
  },
};

const generateBasicTrackingSheet = () => {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Basic Contraction Tracking Sheet</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #333; padding: 8px; text-align: left; }
    th { background-color: #f0f0f0; font-weight: bold; }
    .header { text-align: center; margin-bottom: 20px; }
    .rule-box { border: 2px solid #d32f2f; padding: 15px; margin: 20px 0; background-color: #ffebee; }
    @media print { body { margin: 10px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>CONTRACTION TRACKING LOG</h1>
    <p>Date: __________ Started tracking at: __________</p>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Duration</th>
        <th>Time Since Last</th>
        <th>Intensity (1-10)</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${Array.from(
        { length: 20 },
        (_, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>________________</td>
        </tr>
      `
      ).join("")}
    </tbody>
  </table>
  
  <div class="rule-box">
    <h3 style="text-align: center; color: #d32f2f;">📞 5-1-1 RULE</h3>
    <p style="text-align: center; font-weight: bold;">Call healthcare provider when contractions are:</p>
    <p style="text-align: center; font-size: 18px;">5 minutes apart • 1 minute long • 1 hour consistently</p>
  </div>
  
  <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #666;">
    Generated by Contracking.me - Free Contraction Timer<br>
    https://contracking.me
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "basic-contraction-tracking-sheet.html";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const generateDetailedTrackingSheet = () => {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detailed Contraction Tracking Sheet</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 15px; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #333; padding: 4px; text-align: left; }
    th { background-color: #f0f0f0; font-weight: bold; font-size: 10px; }
    .header { text-align: center; margin-bottom: 15px; }
    .symptoms { margin: 15px 0; }
    .checkbox-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 5px; }
    @media print { body { margin: 5px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>DETAILED CONTRACTION TRACKING</h1>
    <p>Date: __________ Name: __________ Started: __________</p>
  </div>
  
  <div class="symptoms">
    <h3>Other Symptoms (check all that apply)</h3>
    <div class="checkbox-grid">
      <label>☐ Back pain</label>
      <label>☐ Nausea</label>
      <label>☐ Bloody show</label>
      <label>☐ Water broke</label>
      <label>☐ Cramping</label>
      <label>☐ Pressure</label>
    </div>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Start</th>
        <th>End</th>
        <th>Duration</th>
        <th>Frequency</th>
        <th>Intensity</th>
        <th>Position</th>
        <th>Pain Relief</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${Array.from(
        { length: 15 },
        (_, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>______</td>
          <td>______</td>
          <td>_____________</td>
        </tr>
      `
      ).join("")}
    </tbody>
  </table>
  
  <div style="border: 2px solid #d32f2f; padding: 10px; background-color: #ffebee;">
    <h3 style="text-align: center; color: #d32f2f;">📞 CALL PROVIDER WHEN:</h3>
    <p style="text-align: center;">5 minutes apart • 1 minute long • 1 hour consistently</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "detailed-contraction-tracking-sheet.html";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const generateAllSheets = () => {
  // Download a comprehensive package
  const textContent = `CONTRACTION TRACKING SHEETS
===========================

BASIC TRACKING INSTRUCTIONS
---------------------------
1. Start timing when contractions become regular
2. Record start time, end time, and calculate duration
3. Note time between contractions (frequency)
4. Track intensity on scale of 1-10
5. Call provider when: 5 minutes apart, 1 minute long, 1 hour consistently

DETAILED TRACKING NOTES
-----------------------
- Track other symptoms (back pain, nausea, bloody show, water breaking)
- Note position during contractions
- Record any pain relief methods used
- Include notes about how you're feeling

EMERGENCY SIGNS - CALL 911
--------------------------
• Severe bleeding
• Water breaks with green/brown fluid
• Cord prolapse
• Severe headache with vision changes
• Sudden severe abdominal pain
• Baby's movements decrease significantly

PRINTABLE SHEETS INCLUDED
------------------------
1. Basic Contraction Tracking Sheet (20 entries)
2. Detailed Contraction Tracking Sheet (15 entries)
3. Hourly Summary Sheet
4. Partner Support Log
5. Quick Reference Guide with 5-1-1 Rule

TIPS FOR SUCCESS
---------------
• Practice using sheets during Braxton Hicks
• Keep multiple copies handy
• Have partner help with tracking
• Don't forget to include travel time to hospital
• Bring sheets to hospital for provider review

---
Generated by Contracking.me - Free Contraction Timer
https://contracting.me`;

  downloadTextFile(textContent, "contraction-tracking-sheets-complete.txt");
};

export default function PrintableContractionSheetsPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Back Navigation */}
      <Link
        href="/resources"
        className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-6"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Resources
      </Link>

      {/* Header */}
      <header className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <Badge variant="secondary">Tracking</Badge>
          <Badge variant="outline">Printable</Badge>
          <Badge variant="outline">Featured</Badge>
        </div>
        <h1 className="text-4xl font-bold text-foreground mb-4">
          Printable Contraction Tracking Sheets
        </h1>
        <p className="text-xl text-muted-foreground mb-6">
          Physical backup sheets for tracking contractions when digital tools
          aren't available. Perfect for power outages, phone issues, or when you
          prefer pen and paper.
        </p>
        <DownloadSheetsHeaderButtons />
      </header>

      {/* Why Use Printable Sheets */}
      <Card className="mb-8 border-blue-200 bg-blue-50">
        <CardHeader>
          <CardTitle className="text-lg text-blue-700">
            Why Have a Physical Backup?
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2 text-blue-800 text-sm">
            <li>• Phone battery might die during long labor</li>
            <li>• Hospital WiFi or cell service issues</li>
            <li>
              • Some people prefer pen and paper during intense situations
            </li>
            <li>• Healthcare providers can quickly review handwritten logs</li>
            <li>• Multiple people can help track simultaneously</li>
            <li>• Physical backup ensures you never lose your data</li>
          </ul>
        </CardContent>
      </Card>

      {/* Sheet Types */}
      <div className="space-y-8">
        {/* Basic Tracking Sheet */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <Clock className="w-6 h-6 text-green-600" />
              Basic Contraction Tracking Sheet
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Simple table format for tracking contraction start time, duration,
              and frequency. Perfect for early labor.
            </p>

            <div className="bg-white border border-gray-300 rounded-lg p-6 mb-4">
              <div className="text-center mb-4">
                <h3 className="font-bold text-lg">CONTRACTION TRACKING LOG</h3>
                <p className="text-sm text-muted-foreground">
                  Date: __________ Started tracking at: __________
                </p>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border border-gray-300 p-2 text-left">
                        #
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        Start Time
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        End Time
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        Duration
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        Time Since Last
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        Intensity (1-10)
                      </th>
                      <th className="border border-gray-300 p-2 text-left">
                        Notes
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...Array(8)].map((_, i) => (
                      <tr key={i}>
                        <td className="border border-gray-300 p-2">{i + 1}</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">
                          ________________
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="mt-4 p-3 bg-purple-100 border border-purple-200 rounded">
                <p className="text-purple-800 text-sm font-medium text-center">
                  📞 Call healthcare provider when: 5 minutes apart • 1 minute
                  long • 1 hour consistently
                </p>
              </div>
            </div>

            <div className="flex justify-center">
              <DownloadBasicSheetButton />
            </div>
          </CardContent>
        </Card>

        {/* Detailed Tracking Sheet */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <BarChart3 className="w-6 h-6 text-purple-600" />
              Detailed Contraction Log
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Comprehensive tracking sheet with space for additional symptoms,
              positions, and pain management techniques.
            </p>

            <div className="bg-white border border-gray-300 rounded-lg p-6 mb-4">
              <div className="text-center mb-4">
                <h3 className="font-bold text-lg">DETAILED LABOR LOG</h3>
                <div className="grid md:grid-cols-2 gap-4 text-sm mt-2">
                  <p>Date: __________ Name: __________________</p>
                  <p>Started tracking: _______ Provider contacted: _______</p>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-4">
                <div>
                  <h4 className="font-semibold mb-2">
                    Other Symptoms (check all that apply)
                  </h4>
                  <div className="grid grid-cols-2 gap-1 text-sm">
                    <label>□ Back pain</label>
                    <label>□ Nausea</label>
                    <label>□ Bloody show</label>
                    <label>□ Water broke</label>
                    <label>□ Pressure</label>
                    <label>□ Diarrhea</label>
                  </div>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">Pain Management Used</h4>
                  <div className="grid grid-cols-2 gap-1 text-sm">
                    <label>□ Breathing</label>
                    <label>□ Movement</label>
                    <label>□ Massage</label>
                    <label>□ Heat/Cold</label>
                    <label>□ Shower/Bath</label>
                    <label>□ Positions</label>
                  </div>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-xs border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border border-gray-300 p-1">#</th>
                      <th className="border border-gray-300 p-1">Start Time</th>
                      <th className="border border-gray-300 p-1">Duration</th>
                      <th className="border border-gray-300 p-1">Frequency</th>
                      <th className="border border-gray-300 p-1">Intensity</th>
                      <th className="border border-gray-300 p-1">Position</th>
                      <th className="border border-gray-300 p-1">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...Array(10)].map((_, i) => (
                      <tr key={i}>
                        <td className="border border-gray-300 p-1">{i + 1}</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">________</td>
                        <td className="border border-gray-300 p-1">
                          _____________
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="flex justify-center">
              <DownloadDetailedSheetButton />
            </div>
          </CardContent>
        </Card>

        {/* Quick Reference Sheet */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <Calculator className="w-6 h-6 text-orange-600" />
              Quick Reference & Calculation Guide
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Handy reference sheet with timing calculations and the 5-1-1 rule.
              Keep this visible while tracking.
            </p>

            <div className="bg-white border border-gray-300 rounded-lg p-6 mb-4">
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h3 className="font-bold text-lg mb-3 text-center">
                    🕐 TIMING GUIDE
                  </h3>

                  <div className="space-y-3">
                    <div className="p-3 bg-blue-50 border border-blue-200 rounded">
                      <h4 className="font-semibold text-blue-700 mb-2">
                        How to Calculate Frequency
                      </h4>
                      <p className="text-blue-800 text-sm">
                        Time from the START of one contraction to the START of
                        the next contraction.
                      </p>
                      <p className="text-blue-800 text-xs mt-1">
                        Example: Contraction at 2:00 PM, next at 2:05 PM = 5
                        minutes apart
                      </p>
                    </div>

                    <div className="p-3 bg-green-50 border border-green-200 rounded">
                      <h4 className="font-semibold text-green-700 mb-2">
                        How to Calculate Duration
                      </h4>
                      <p className="text-green-800 text-sm">
                        Time from when contraction starts to when it completely
                        ends.
                      </p>
                      <p className="text-green-800 text-xs mt-1">
                        Example: Starts 2:00 PM, ends 2:01:30 PM = 90 seconds
                        long
                      </p>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="font-bold text-lg mb-3 text-center">
                    📞 5-1-1 RULE
                  </h3>

                  <div className="p-4 bg-red-50 border border-red-200 rounded">
                    <h4 className="font-semibold text-red-700 mb-2 text-center">
                      Call Healthcare Provider When:
                    </h4>
                    <div className="grid grid-cols-3 gap-2 text-center">
                      <div className="p-2 bg-white border border-red-200 rounded">
                        <div className="text-2xl font-bold text-red-700">5</div>
                        <div className="text-xs text-red-600">
                          Minutes Apart
                        </div>
                      </div>
                      <div className="p-2 bg-white border border-red-200 rounded">
                        <div className="text-2xl font-bold text-red-700">1</div>
                        <div className="text-xs text-red-600">Minute Long</div>
                      </div>
                      <div className="p-2 bg-white border border-red-200 rounded">
                        <div className="text-2xl font-bold text-red-700">1</div>
                        <div className="text-xs text-red-600">Hour Pattern</div>
                      </div>
                    </div>
                  </div>

                  <div className="mt-3 p-3 bg-yellow-50 border border-yellow-200 rounded">
                    <h4 className="font-semibold text-yellow-700 mb-1">
                      Quick Calculation
                    </h4>
                    <p className="text-yellow-800 text-xs">
                      If you have 12+ contractions in an hour that are 1+
                      minutes long, call your provider.
                    </p>
                  </div>
                </div>
              </div>

              <div className="mt-6 p-4 bg-purple-50 border border-purple-200 rounded">
                <h4 className="font-semibold text-purple-700 mb-2">
                  Emergency Signs - Call 911
                </h4>
                <div className="grid md:grid-cols-2 gap-2 text-purple-800 text-sm">
                  <ul className="space-y-1">
                    <li>• Severe bleeding</li>
                    <li>• Green/brown amniotic fluid</li>
                    <li>• Cord prolapse</li>
                  </ul>
                  <ul className="space-y-1">
                    <li>• Severe headache + vision changes</li>
                    <li>• Baby stops moving</li>
                    <li>• Feel urge to push</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="flex justify-center">
              <DownloadBasicSheetButton />
            </div>
          </CardContent>
        </Card>

        {/* Hourly Summary Sheet */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <BarChart3 className="w-6 h-6 text-blue-600" />
              Hourly Summary Tracking Sheet
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Track contraction patterns by hour to identify progression and
              communicate clearly with healthcare providers.
            </p>

            <div className="bg-white border border-gray-300 rounded-lg p-6 mb-4">
              <div className="text-center mb-4">
                <h3 className="font-bold text-lg">
                  HOURLY CONTRACTION SUMMARY
                </h3>
                <p className="text-sm">
                  Date: __________ Name: __________________
                </p>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-sm border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border border-gray-300 p-2">
                        Time Period
                      </th>
                      <th className="border border-gray-300 p-2">
                        # of Contractions
                      </th>
                      <th className="border border-gray-300 p-2">
                        Average Duration
                      </th>
                      <th className="border border-gray-300 p-2">
                        Average Frequency
                      </th>
                      <th className="border border-gray-300 p-2">
                        Intensity Range
                      </th>
                      <th className="border border-gray-300 p-2">
                        Pattern Notes
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      "12:00 AM - 1:00 AM",
                      "1:00 AM - 2:00 AM",
                      "2:00 AM - 3:00 AM",
                      "3:00 AM - 4:00 AM",
                      "4:00 AM - 5:00 AM",
                      "5:00 AM - 6:00 AM",
                    ].map((time, i) => (
                      <tr key={i}>
                        <td className="border border-gray-300 p-2 font-medium">
                          {time}
                        </td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">_______</td>
                        <td className="border border-gray-300 p-2">
                          ______________
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="mt-4 p-3 bg-green-100 border border-green-200 rounded">
                <h4 className="font-semibold text-green-700 mb-1">
                  Provider Communication
                </h4>
                <p className="text-green-800 text-sm">
                  Called provider at: _______ Advice given:
                  _________________________________
                </p>
              </div>
            </div>

            <div className="flex justify-center">
              <DownloadDetailedSheetButton />
            </div>
          </CardContent>
        </Card>

        {/* Partner's Tracking Sheet */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">
              Partner's Support Tracking Sheet
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Special sheet designed for birth partners to track contractions
              and support techniques. Includes comfort measures and
              encouragement prompts.
            </p>

            <div className="bg-white border border-gray-300 rounded-lg p-6 mb-4">
              <div className="text-center mb-4">
                <h3 className="font-bold text-lg">PARTNER SUPPORT LOG</h3>
                <p className="text-sm">
                  Labor Partner: __________ Date: __________
                </p>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-4">
                <div>
                  <h4 className="font-semibold mb-2">Comfort Measures Tried</h4>
                  <div className="grid grid-cols-2 gap-1 text-sm">
                    <label>□ Back massage</label>
                    <label>□ Breathing together</label>
                    <label>□ Position changes</label>
                    <label>□ Walking</label>
                    <label>□ Shower/bath</label>
                    <label>□ Music/relaxation</label>
                    <label>□ Ice chips</label>
                    <label>□ Cool cloth</label>
                  </div>
                </div>
                <div>
                  <h4 className="font-semibold mb-2">Mom's Preferences</h4>
                  <div className="text-sm space-y-1">
                    <p>Most helpful: ____________________</p>
                    <p>Least helpful: ____________________</p>
                    <p>Wants during contractions: __________</p>
                    <p>Wants between contractions: ________</p>
                  </div>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-xs border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border border-gray-300 p-1">Time</th>
                      <th className="border border-gray-300 p-1">Duration</th>
                      <th className="border border-gray-300 p-1">Frequency</th>
                      <th className="border border-gray-300 p-1">Mom's Mood</th>
                      <th className="border border-gray-300 p-1">
                        Support Given
                      </th>
                      <th className="border border-gray-300 p-1">Notes</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...Array(8)].map((_, i) => (
                      <tr key={i}>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_____</td>
                        <td className="border border-gray-300 p-1">_______</td>
                        <td className="border border-gray-300 p-1">
                          _________
                        </td>
                        <td className="border border-gray-300 p-1">
                          ___________
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="flex justify-center">
              <DownloadDetailedSheetButton />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Usage Instructions */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center gap-2">
            <Printer className="w-6 h-6 text-gray-600" />
            Printing and Usage Instructions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold mb-3">Printing Tips</h4>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Print on standard 8.5" x 11" paper</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Use black ink for best readability</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Print multiple copies (home, car, hospital bag)</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Laminate reference sheets for durability</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Attach pen or pencil to clipboard</span>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-3">Usage Tips</h4>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Start with the basic sheet for early labor</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Switch to detailed sheet if labor progresses</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Let your partner help with tracking</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Keep reference sheet visible at all times</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckSquare className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>Bring completed sheets to the hospital</span>
                </li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Digital vs Physical */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle className="text-2xl">
            Digital vs. Physical Tracking
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold mb-3 text-green-700">
                Benefits of Digital (Recommended)
              </h4>
              <ul className="space-y-2 text-sm">
                <li>• Automatic calculations and timing</li>
                <li>• Visual charts and pattern recognition</li>
                <li>• No math required during contractions</li>
                <li>• Easy to share data with providers</li>
                <li>• Built-in 5-1-1 rule alerts</li>
                <li>• Can't lose or forget data</li>
              </ul>
              <div className="mt-4">
                <Link href="/">
                  <Button size="sm" className="w-full">
                    Use Digital Timer
                  </Button>
                </Link>
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-3 text-orange-700">
                When to Use Physical Sheets
              </h4>
              <ul className="space-y-2 text-sm">
                <li>• Phone battery dies</li>
                <li>• No internet/cell service</li>
                <li>• Prefer pen and paper</li>
                <li>• Multiple people helping track</li>
                <li>• Backup for peace of mind</li>
                <li>• Healthcare provider prefers paper logs</li>
              </ul>
              <div className="mt-4">
                <DownloadAllSheetsButton size="sm" className="w-full" />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Best Practices */}
      <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg p-6 mb-8">
        <h3 className="font-semibold text-foreground mb-4">
          Best Practices for Contraction Tracking
        </h3>
        <div className="grid md:grid-cols-2 gap-6 text-sm">
          <ul className="space-y-2">
            <li>• Start tracking when contractions become regular</li>
            <li>• Use a watch or clock with a second hand</li>
            <li>• Track for at least one hour before calling provider</li>
            <li>• Note any changes in pattern or intensity</li>
          </ul>
          <ul className="space-y-2">
            <li>• Don't obsess over perfect timing</li>
            <li>• Focus on overall patterns, not individual contractions</li>
            <li>• Include other symptoms and comfort measures</li>
            <li>• Bring your tracking log to the hospital</li>
          </ul>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="text-center space-y-4">
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <DownloadAllSheetsButton size="lg" />
          <Link href="/">
            <Button size="lg">Use Digital Timer Instead</Button>
          </Link>
        </div>
        <p className="text-sm text-muted-foreground">
          Print these sheets before 36 weeks and keep them easily accessible
        </p>
      </div>

      {/* Related Resources */}
      <section className="mt-12 pt-8 border-t border-border">
        <h3 className="text-xl font-semibold text-foreground mb-6">
          Related Resources
        </h3>
        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">
                <Link
                  href="/how-to-use"
                  className="hover:text-primary transition-colors"
                >
                  How to Use the Digital Timer
                </Link>
              </CardTitle>
              <CardDescription>
                Learn how to use our digital contraction timer effectively.
              </CardDescription>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">
                <Link
                  href="/blog/understanding-different-types-contractions"
                  className="hover:text-primary transition-colors"
                >
                  Understanding Different Types of Contractions
                </Link>
              </CardTitle>
              <CardDescription>
                Learn to distinguish between different types of contractions.
              </CardDescription>
            </CardHeader>
          </Card>
        </div>
      </section>
    </div>
  );
}

