"use client";

import { Button } from "@/components/ui/button";
import { downloadTextFile } from "@/lib/download-utils";
import { Download, Printer } from "lucide-react";

function generateBasicTrackingSheet() {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Basic Contraction Tracking Sheet</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #333; padding: 8px; text-align: left; }
    th { background-color: #f0f0f0; font-weight: bold; }
    .header { text-align: center; margin-bottom: 20px; }
    .rule-box { border: 2px solid #d32f2f; padding: 15px; margin: 20px 0; background-color: #ffebee; }
    @media print { body { margin: 10px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>CONTRACTION TRACKING LOG</h1>
    <p>Date: __________ Started tracking at: __________</p>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Duration</th>
        <th>Time Since Last</th>
        <th>Intensity (1-10)</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${Array.from(
        { length: 20 },
        (_, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>_______</td>
          <td>________________</td>
        </tr>
      `
      ).join("")}
    </tbody>
  </table>
  
  <div class="rule-box">
    <h3 style="text-align: center; color: #d32f2f;">📞 5-1-1 RULE</h3>
    <p style="text-align: center; font-weight: bold;">Call healthcare provider when contractions are:</p>
    <p style="text-align: center; font-size: 18px;">5 minutes apart • 1 minute long • 1 hour consistently</p>
  </div>
  
  <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #666;">
    Generated by Contracking.me - Free Contraction Timer<br>
    https://contracking.me
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "basic-contraction-tracking-sheet.html";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateDetailedTrackingSheet() {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detailed Contraction Tracking Sheet</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 15px; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #333; padding: 4px; text-align: left; }
    th { background-color: #f0f0f0; font-weight: bold; font-size: 10px; }
    .header { text-align: center; margin-bottom: 15px; }
    .symptoms { margin: 15px 0; }
    .checkbox-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 5px; }
    @media print { body { margin: 5px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>DETAILED CONTRACTION TRACKING</h1>
    <p>Date: __________ Name: __________ Started: __________</p>
  </div>
  
  <div class="symptoms">
    <h3>Other Symptoms (check all that apply)</h3>
    <div class="checkbox-grid">
      <label>☐ Back pain</label>
      <label>☐ Nausea</label>
      <label>☐ Bloody show</label>
      <label>☐ Water broke</label>
      <label>☐ Cramping</label>
      <label>☐ Pressure</label>
    </div>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Start</th>
        <th>End</th>
        <th>Duration</th>
        <th>Frequency</th>
        <th>Intensity</th>
        <th>Position</th>
        <th>Pain Relief</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${Array.from(
        { length: 15 },
        (_, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>____</td>
          <td>______</td>
          <td>______</td>
          <td>_____________</td>
        </tr>
      `
      ).join("")}
    </tbody>
  </table>
  
  <div style="border: 2px solid #d32f2f; padding: 10px; background-color: #ffebee;">
    <h3 style="text-align: center; color: #d32f2f;">📞 CALL PROVIDER WHEN:</h3>
    <p style="text-align: center;">5 minutes apart • 1 minute long • 1 hour consistently</p>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "detailed-contraction-tracking-sheet.html";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateAllSheets() {
  const textContent = `CONTRACTION TRACKING SHEETS
===========================

BASIC TRACKING INSTRUCTIONS
---------------------------
1. Start timing when contractions become regular
2. Record start time, end time, and calculate duration
3. Note time between contractions (frequency)
4. Track intensity on scale of 1-10
5. Call provider when: 5 minutes apart, 1 minute long, 1 hour consistently

DETAILED TRACKING NOTES
-----------------------
- Track other symptoms (back pain, nausea, bloody show, water breaking)
- Note position during contractions
- Record any pain relief methods used
- Include notes about how you're feeling

EMERGENCY SIGNS - CALL 911
--------------------------
• Severe bleeding
• Water breaks with green/brown fluid
• Cord prolapse
• Severe headache with vision changes
• Sudden severe abdominal pain
• Baby's movements decrease significantly

PRINTABLE SHEETS INCLUDED
------------------------
1. Basic Contraction Tracking Sheet (20 entries)
2. Detailed Contraction Tracking Sheet (15 entries)
3. Hourly Summary Sheet
4. Partner Support Log
5. Quick Reference Guide with 5-1-1 Rule

TIPS FOR SUCCESS
---------------
• Practice using sheets during Braxton Hicks
• Keep multiple copies handy
• Have partner help with tracking
• Don't forget to include travel time to hospital
• Bring sheets to hospital for provider review

---
Generated by Contracking.me - Free Contraction Timer
https://contracking.me`;

  downloadTextFile(textContent, "contraction-tracking-sheets-complete.txt");
}

interface DownloadSheetsButtonsProps {
  className?: string;
  size?: "sm" | "lg" | "default";
  variant?: "default" | "outline";
}

export function DownloadSheetsHeaderButtons({
  className,
}: DownloadSheetsButtonsProps) {
  return (
    <div className={`flex gap-4 mb-6 ${className}`}>
      <Button onClick={generateAllSheets}>
        <Download className="w-4 h-4 mr-2" />
        Download All Sheets
      </Button>
      <Button variant="outline" onClick={generateBasicTrackingSheet}>
        <Printer className="w-4 h-4 mr-2" />
        Print Basic Sheet
      </Button>
    </div>
  );
}

export function DownloadBasicSheetButton({
  size = "default",
  variant = "outline",
}: DownloadSheetsButtonsProps) {
  return (
    <Button variant={variant} size={size} onClick={generateBasicTrackingSheet}>
      <Download className="w-4 h-4 mr-2" />
      Download Basic Sheet
    </Button>
  );
}

export function DownloadDetailedSheetButton({
  size = "default",
  variant = "outline",
}: DownloadSheetsButtonsProps) {
  return (
    <Button
      variant={variant}
      size={size}
      onClick={generateDetailedTrackingSheet}
    >
      <Download className="w-4 h-4 mr-2" />
      Download Detailed Sheet
    </Button>
  );
}

export function DownloadAllSheetsButton({
  size = "default",
  variant = "outline",
}: DownloadSheetsButtonsProps) {
  return (
    <Button variant={variant} size={size} onClick={generateAllSheets}>
      <Download className="w-4 h-4 mr-2" />
      Download All Tracking Sheets
    </Button>
  );
}

